### PR TITLE
Update DialogicAnimaResources.gd

### PR DESCRIPTION
**Pull request by TheMeddlingMechanic**
Hi,
This is theMeddlingMechanic from the dialogic discord (sorry for taking a while). I've added a single line of of code (line 39) on the DialogicAnimaResources.gd script. This is to account for developers who use PckEncryption in their game builds.

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
@zaknafean This seems like a pretty simple PR, anything you need to test before we can merge this?

**Comment by zaknafean** [comment]
Unfortunately it may break non encrypted builds as written. I gotta add a branch of some kind that can determine  if you're encrypted or not.

**Comment by TheMeddlingMechanic** [comment]
Hi guys, I believe this shouldn't cause issues like that as it adds a new line, replacing both .gdc and .gde with .gd in the saved list. Feel free to test it, but if I remember correctly, that should work.

**Comment by Jowan-Spooner** [comment]
Hmmm... I'm unable to test this as I don't have a dialogic 1 environment anymore. 
Wouldn't it need to be something like
```
filtered.push_back(file.replace('.gde', '.gd').replace('.gdc', '.gd'))
```
So any file is only added once and depending on what "wrong" extension it has they get corrected?

**Comment by TheMeddlingMechanic** [comment]
Hmm, this could be the case, I'm not home at the moment, but when I am I'll record myself testing this for both encrypted and not (I can print out the list and check the logs). I'll get back to you with the recording once I've got an answer.

**Comment by TheMeddlingMechanic** [comment]
Actually, I doubt this will be an issue, as every script in the pck should be the same type (gdc vs gde), so only one of these lines of code should make a difference,
but I'll still test it once I have the chance, just in case.

**Comment by TheMeddlingMechanic** [comment]
I didn't record this in the end, just added another commit because of the obvious meaning of the docs for that method.

**Comment by zaknafean** [comment]
Confirmed it still works on non-encrypted exports just fine. Thanks for the PR @TheMeddlingMechanic , merging it in now.

**Pull request merged**
