### PR TITLE
Fix static call warnings for `get_editor_interface()`

### PR DESCRIPTION
**Pull request by juliohq**
This PR fixes warnings caused by calling `get_editor_interface()` (`STATIC_CALLED_ON_INSTANCE`).

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
I've not tested this one yet, but using EditorInterface directly usually results in errors on exported projects, as godot decides not to include the editor classes/singletons in the export. 
Maybe this works, but it needs to be properly tested.
The other PR's seem cool though. Thanks a lot for all this cleanup😍!

**Comment by juliohq** [comment]
I think we can hold off on it in this case. Do those errors happen even for plugin code that isn't executed directly in an exported game?

**Comment by Jowan-Spooner** [comment]
I think so, unless the whole script goes unused (for example the DialogicUtil script is used in exported games while the plugin.gd script is only used in editor). It's usually parse errors (when the script is loaded), due to finding an "unknown" class name.

**Comment by Jowan-Spooner** [comment]
Yeah sorry @juliohq, I can confirm that this breaks exports, so I would close this PR unless you object.

I'm curious though, when are you even getting these warnings? I don't think I'm getting them or I'm missing it somehow 🙈.

**Comment by juliohq** [comment]
Alright, in this case this PR should be closed. As for the warnings, they suddenly stopped to show up for me. I'm closing it rn.

**Comment by Jowan-Spooner** [comment]
If the warnings come up again, feel free to create an issue for it and we will see what can be done!

**Pull request closed without merging**
