### PR TITLE
Choices: add array boundary checking

### PR DESCRIPTION
**Pull request by endaye**
* to fix this bug below
image

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
This looks alright, but it fixes a symptom, I'd be really curious why this happens.

**Comment by endaye** [comment]
I am not sure. Maybe it was caused by what I called `Dialogic.clear()` when it's running.

**Comment by zaknafean** [comment]
Does that cause it to happen consistently? Can you share the code?

**Review by zaknafean — CHANGES_REQUESTED** [review]
While I generally like bounds checking, this feels like a bandage to a problem that maybe shouldn't exist. We really need an example of when this happens here specifically, and why. Do you have a small project we could review?

**Pull request closed without merging**
