### PR TITLE
Add option to include simple and/or full event history in savegame

### PR DESCRIPTION
**Pull request by jrb0001**
Simple and full event history can be toggled separately. If one option is enabled:
- Include that history in Dialogic.get_full_state() / Save.save().
- On Dialogic.load_full_state() / Save.load() replace that history with the history from the savegame.
  - If the savegame doesn't contain that history, clear it.
  - Events appended to the full event history between the clear_game_state() and the load_game_state() are dropped intentionally.
- On Dialogic.clear(FULL_CLEAR), clear that history.

The changes to the text event are needed to avoid duplicating the last entry in the simple history after a save+load. This also makes the text show up immediately after loading instead of the normal typing style.

Feel free to suggest a better option name or tooltip.

### CODE REVIEW

**Comment by Jowan-Spooner** [comment]
This looks good to me on the surface, will try to take a closer look the coming days.

**Comment by Jowan-Spooner** [comment]
I think this makes sense. I made some changes to follow the gdscript style guide. 
I'm not entirely sure whether having these histories get erased on clear() is a good thing, but am willing to merge this and potentially adjust the behaviour in future PR's. 

This incidentally fixes #1316

**Comment by Jowan-Spooner** [comment]
Thanks and congrats on your first PR!

**Comment by jrb0001** [comment]
Thanks for the cleanup!

I thought about adding another option for the clear behavior but decided against it in the end. Enabling the save/load behavior more or less makes it part of the game state, like variables. So I wanted to mirror their behavior for consistency.

I can only see the use case where a game has many relatively short and repeatable timelines and uses dialogic variables as temporaries while keeping the real state outside dialogic. And unless such a game supports saving inside such dialogue, it wouldn't use the dialogic save system anyway so it has no reason to enable the option.

I am not against adding a separate clear option, but I also didn't want to clutter the settings tab with something that might never be used (independently).

**Pull request merged**
